name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '_bmad/**'
      - '_bmad-output/**'
      - 'docs/**'
  pull_request:
    branches:
      - main

env:
  REGISTRY: harbor.g-eye.io
  IMAGE_NAME: elgato/elgato-photo

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npx tsc --noEmit

      - name: Generate Prisma client
        run: npx prisma generate

  build-and-push:
    name: Build & Push Docker
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: gitea.event_name == 'push' && gitea.ref == 'refs/heads/main'
    container:
      image: gcr.io/kaniko-project/executor:debug
      options: --entrypoint ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate image tags
        id: tags
        run: |
          SHORT_SHA=$(echo "${{ gitea.sha }}" | cut -c1-7)
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "sha_tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "timestamp_tag=${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Setup Kaniko auth
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASS: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          mkdir -p /kaniko/.docker
          AUTH=$(echo -n "${HARBOR_USER}:${HARBOR_PASS}" | base64)
          cat > /kaniko/.docker/config.json << EOF
          {
            "auths": {
              "${{ env.REGISTRY }}": {
                "auth": "${AUTH}"
              }
            }
          }
          EOF

      - name: Build and push with Kaniko
        run: |
          /kaniko/executor \
            --context "${GITHUB_WORKSPACE}" \
            --dockerfile "${GITHUB_WORKSPACE}/Dockerfile" \
            --destination "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" \
            --destination "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.sha_tag }}" \
            --destination "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.timestamp_tag }}" \
            --build-arg "APP_VERSION=${{ gitea.sha }}" \
            --cache=true

      - name: Summary
        run: |
          echo "=== Docker Image Built with Kaniko ==="
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Image: ${{ env.IMAGE_NAME }}"
          echo "Tags: latest, ${{ steps.tags.outputs.sha_tag }}, ${{ steps.tags.outputs.timestamp_tag }}"
