name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '_bmad/**'
      - '_bmad-output/**'
      - 'docs/**'
  pull_request:
    branches:
      - main

env:
  REGISTRY: harbor.g-eye.io
  IMAGE_NAME: elgato/elgato-photo
  BUILDKIT_HOST: tcp://buildkit.dev.svc.cluster.local:1234

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    container:
      image: node:20-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npx tsc --noEmit

      - name: Generate Prisma client
        run: npx prisma generate

  build-and-push:
    name: Build & Push Docker
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: gitea.event_name == 'push' && gitea.ref == 'refs/heads/main'
    container:
      image: docker:27-cli
      options: --network=host
      volumes:
        - /buildkit-certs:/buildkit-certs:ro

    steps:
      - name: Checkout
        env:
          GITEA_TOKEN: ${{ github.token }}
        run: |
          git clone --depth 1 https://oauth2:${GITEA_TOKEN}@gitea.g-eye.io/${{ gitea.repository }}.git .
          git fetch origin ${{ gitea.sha }} --depth 1
          git checkout ${{ gitea.sha }}

      - name: Install buildx
        run: |
          mkdir -p ~/.docker/cli-plugins
          wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.14.0/buildx-v0.14.0.linux-amd64
          chmod +x ~/.docker/cli-plugins/docker-buildx

      - name: Create buildx builder with remote BuildKit
        run: |
          docker buildx create \
            --name remote-buildkit \
            --driver remote \
            --driver-opt cacert=/buildkit-certs/ca.pem,cert=/buildkit-certs/cert.pem,key=/buildkit-certs/key.pem \
            ${{ env.BUILDKIT_HOST }}
          docker buildx use remote-buildkit
          docker buildx inspect --bootstrap

      - name: Login to Harbor Registry
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASS: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          echo "${HARBOR_PASS}" | docker login ${{ env.REGISTRY }} -u "${HARBOR_USER}" --password-stdin

      - name: Generate image tags
        id: tags
        run: |
          SHORT_SHA=$(echo "${{ gitea.sha }}" | cut -c1-7)
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "sha_tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "timestamp_tag=${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.sha_tag }} \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.timestamp_tag }} \
            --build-arg APP_VERSION=${{ gitea.sha }} \
            .

      - name: Summary
        run: |
          echo "=== Docker Image Built with Remote BuildKit ==="
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Image: ${{ env.IMAGE_NAME }}"
          echo "Tags: latest, ${{ steps.tags.outputs.sha_tag }}, ${{ steps.tags.outputs.timestamp_tag }}"
          echo "Platforms: linux/amd64, linux/arm64"
